import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { Toaster } from "~/components/ui/sonner";

import { ThemeProvider } from "~/components/providers/theme-provider";
import { Sidebar } from "./_components/sidebar/sidebar";
import { Topbar } from "./_components/topbar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex flex-col md:flex-row">
              <div className="hidden w-1/4 md:block">
                <Sidebar />
              </div>
              <div className="md:hidden sticky bg-background z-50 top-0">
                <Topbar />
              </div>
              <div className="w-full md:w-3/4">{children}</div>
            </div>
            <Toaster />
          </ThemeProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
